/* eslint-disable react/prop-types */
import { arrayHasData } from '@/helpers/helpers';
import React from 'react';

const RevenuePage = ({ revenues }) => {
  const totalPrice = arrayHasData(revenues)
    ? 0
    : revenues
        ?.reduce(
          (acc, currentValue) =>
            acc + currentValue?.price * currentValue?.quantity,
          0,
        )
        .toFixed(2);

  return (
    <div>
      <div className="flex justify-between my-4">
        <h1 className="text-lg ml-4 font-bold">
          Revenues generated by this product
        </h1>
        <p className="mr-4 font-semibold text-xs">Total: $ {totalPrice}</p>
      </div>
      {arrayHasData(revenues) ? (
        <div className="w-full mt-8">
          <p className="font-bold text-xl text-center">
            No Revenues generated by this product
          </p>
        </div>
      ) : (
        <table className="w-full text-sm text-left">
          <thead className="text-l text-gray-700 uppercase">
            <tr>
              <th scope="col" className="px-6 py-3">
                Quantity Sold
              </th>
              <th scope="col" className="px-6 py-3">
                Price Generated
              </th>
              <th scope="col" className="px-6 py-3">
                Date
              </th>
            </tr>
          </thead>
          <tbody>
            {revenues?.map((revenue, index) => (
              <tr key={index} className="bg-white">
                <td className="px-6 py-2">{revenue?.quantity}</td>
                <td className="px-6 py-2">
                  $ {revenue?.price * revenue?.quantity}
                </td>
                <td className="px-6 py-2">{revenue?.date?.substring(0, 10)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

export default RevenuePage;
